server: 
 port: 5001
 error: 
  include-binding-errors: always
  include-message: always
  include-exception: true
  
spring:
 datasource:
  hikari:
   autoCommit : false
  url: jdbc:postgresql://localhost:5433/saloonBookingService
  username: postgres
  password: aylaadem233
  driver-class-name: org.postgresql.Driver
  
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   '[hibernate.format_sql]': true

info:
 application: 
  name: 'saloon service' 
  description: 'This is a saloon microservice for saloon booking system'
  version: '@project.version@' 
   
